Repository jhnc-oss/meta-protos, pull requests merged in 2021-07, with the labels that each got.

#6 Provide recipe to build latest version of sshpass
  recipes-oss/packagegroups/packagegroup-protos-oss.bb
  recipes-oss/sshpass/sshpass.inc
  recipes-oss/sshpass/sshpass_1.0.9.bb
Labels: bug

#8 oelint-adv CI
  .github/workflows/ci.yml
  README.md
  oelint.rules
  requirements.txt
Labels: ci

#12 Recipes for cpputest, cppcheck and cmocka
  recipes-oss/cmocka/cmocka.inc
  recipes-oss/cmocka/cmocka_1.1.5.bb
  recipes-oss/cppcheck/cppcheck.inc
  recipes-oss/cppcheck/cppcheck_2.5.bb
  recipes-oss/cpputest/cpputest.inc
  recipes-oss/cpputest/cpputest_4.0.bb
  recipes-oss/packagegroups/packagegroup-protos-oss.bb
Labels: recipe

#14 Closes #13
  conf/templates/bblayers.conf.sample
  conf/templates/local.conf.sample
  meta/classes/extra_mirrors.bbclass
  meta/conf/layer.conf
  recipes-oss/cmocka/cmocka_1.1.5.bb
  recipes-oss/cppcheck/cppcheck_2.5.bb
  recipes-oss/cpputest/cpputest_4.0.bb
  recipes-oss/packagegroups/packagegroup-protos-oss.bb
  recipes-oss/sshpass/sshpass.inc
  recipes-oss/sshpass/sshpass_1.0.9.bb
Labels: fix
