Repository jhnc-oss/meta-protos, pull requests merged in 2021-11, with the labels that each got.

#49 Add latest minizip (3.0.3)
  README.md
  recipes-oss/cppcheck/cppcheck_2.6.bb
  recipes-oss/minizip-ng/minizip.inc
  recipes-oss/minizip-ng/minizip_3.0.3.bb
  recipes-oss/packagegroups/packagegroup-protos-oss.bb
Labels: recipe

#51 recipe: fix sshpass
  recipes-oss/sshpass/sshpass_1.09.bb
Labels: bug, fix

#52 Overlay to unbreak recipes needing python2 legacy
  conf/templates/bblayers.conf.sample
  meta-oe/conf/layer.conf/layer.conf
  meta-oe/recipes-devtools/sip/sip_4.19.16.bb
Labels: fix

#53 recipe: update cmake-extra-modules (CEM v5.88.0)
  recipes-devtools/extra-cmake-modules/extra-cmake-modules_5.88.0.bb
Labels: enhancement, recipe

#54 fix: unbreak target packagegroup-protos-oss
  recipes-oss/packagegroups/packagegroup-protos-oss.bb
Labels: bug, fix

#55 oelint config file
  .github/workflows/ci.yml
  .oelint.cfg
  oelint.rules
  requirements.txt
Labels: enhancement

#56 cleanup: poky DISTRO_VERSION and recipe linting
  conf/distro/protos.conf
  meta-oe/recipes-devtools/sip/sip_4.19.16.bb
Labels: enhancement, recipe, fix
