Repository jhnc-oss/meta-protos, pull requests merged in 2021-09, with the labels that each got.

#31 Update step branch
  .github/workflows/ci.yml
Labels: ci

#34 recipe: update cmake-extra-modules (CEM v5.86.0)
  recipes-devtools/extra-cmake-modules/extra-cmake-modules_5.86.0.bb
Labels: out-of-date_sw

#36 layer: add meta-mingw and meta-selinux
  README.md
  conf/templates/bblayers.conf.sample
Labels: enhancement, layer
